@echo off

set CMAKE_CONFIGURE_FLAGS= ^
	-DLLVM_INCLUDE_TESTS=OFF ^
	-DLLVM_INCLUDE_UTILS=OFF

set CONFIGURATION=Debug

if "%CONFIGURATION%" == "Debug" (
	set CMAKE_CONFIGURE_FLAGS= ^
		%CMAKE_CONFIGURE_FLAGS% ^
		-DLLVM_INCLUDE_TOOLS=OFF
)

echo CMAKE_CONFIGURE_FLAGS: %CMAKE_CONFIGURE_FLAGS%
