name: GitHub CI

on:
-   push
-   pull_request

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: ${{matrix.TARGET_CPU == 'arm64' && 'windows-11-arm' || 'windows-2022'}}
        env:
            BUILD_PROJECT: llvm
            BUILD_MASTER: false
            LLVM_VERSION: 14.0.6
            FORCE_ARTIFACTS: true

        strategy:
            fail-fast: false
            matrix:
                CRT:
                -   msvcrt
                -   libcmt

                TARGET_CPU:
                # -   x86
                # -   amd64
                -   arm64

                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v6

        -   name: Install
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\install.bat

        -   name: Build and test
            id: BUILD
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\build.bat
                echo DEPLOY_FILE=%DEPLOY_FILE%>>%GITHUB_OUTPUT%

        -   name: Release
            uses: softprops/action-gh-release@v2
            if: startsWith(github.ref, 'refs/tags/') || env.FORCE_ARTIFACTS == 'true'
            env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            with:
                tag_name: ${{env.BUILD_PROJECT}}-${{env.LLVM_VERSION}}
                files: ${{steps.BUILD.outputs.DEPLOY_FILE}}
